apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: shockwater/auth
    context: auth
  - image: shockwater/client
    context: client
  - image: shockwater/tickets
    context: tickets
deploy:
  kubectl:
    manifests:
    - infra/k8s/client-deployment.yaml
    - infra/k8s/auth-deployment.yaml
    - infra/k8s/auth-mongo-deployment.yaml
    - infra/k8s/ingress-service.yaml
    - infra/k8s/tickets-deployment.yaml
    - infra/k8s/tickets-mongo-deployment.yaml
    - infra/k8s/nats-deployment.yaml
