apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: shockwater/auth
    context: auth
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-deployment.yaml
    - infra/k8s/ingress-service.yaml
